<?xml version="1.0"?>
<package format="2">
  <name>robotrainer_bringup</name>
  <version>0.0.0</version>
  <description>The robotrainer_bringup package</description>

  <maintainer email="urduq@student.kit.edu">Peter Wern</maintainer>

  <license>TODO</license>


  <!-- Url tags are optional, but mutiple are allowed, one per tag -->
  <!-- Optional attribute type can be: website, bugtracker, or repository -->
  <!-- Example: -->
  <!-- <url type="website">http://wiki.ros.org/sr2_bringup</url> -->


  <!-- Author tags are optional, mutiple are allowed, one per tag -->
  <!-- Authors do not have to be maintianers, but could be -->
  <!-- Example: -->
  <!-- <author email="jane.doe@example.com">Jane Doe</author> -->

  <buildtool_depend>catkin</buildtool_depend>
  <exec_depend>cob_bringup</exec_depend>
  <exec_depend>cob_default_robot_config</exec_depend>
  <exec_depend>cob_hardware_config</exec_depend>
  <exec_depend>cob_script_server</exec_depend>
  <exec_depend>controller_manager</exec_depend>
  <exec_depend>robotrainer_modalities</exec_depend>
  <exec_depend>robotrainer_panel</exec_depend>
  <exec_depend>robotrainer_config</exec_depend>
  <exec_depend>sr2_bringup</exec_depend>
  <exec_depend>sick_safetyscanners</exec_depend>

  <test_depend>roslaunch</test_depend>

</package>
