## joint_names
joint_names: [fr_caster_rotation_joint, fl_caster_rotation_joint, br_caster_rotation_joint, bl_caster_rotation_joint, fr_caster_r_wheel_joint, fl_caster_r_wheel_joint, br_caster_r_wheel_joint, bl_caster_r_wheel_joint]

## joint_state_controller
joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50
        wheels: &wheels # start front left, counter-clockwise for base_drive_chain compatibility
              - steer: fl_caster_rotation_joint
                drive: fl_caster_r_wheel_joint
                steer_neutral_position: 180.0
              - steer: bl_caster_rotation_joint
                drive: bl_caster_r_wheel_joint
                steer_neutral_position: 180.0
              - steer: br_caster_rotation_joint
                drive: br_caster_r_wheel_joint
                steer_neutral_position: 180.0
              - steer: fr_caster_rotation_joint
                drive: fr_caster_r_wheel_joint
                steer_neutral_position: 180.0
  
twist_controller:
        use_fts: true
        type: robotrainer_controllers/FTSAdaptiveController
        required_drive_mode: 3
        publish_rate: 50
        max_rot_velocity: 1.0 #0.2
        max_trans_velocity: 1.5 #0.2
        FTSBaseController:
                simulate: True
                update_rate: 200.0
                # trigger inversion of y and rotation outputs
                y_reversed: False
                rot_reversed: False
                # scale for negative x-direction
                backwards_max_force_scale: 0.5
                backwards_max_vel_scale: 0.7 #0.25
                # trigger using controllers
                x_force_controller: True
                y_force_controller: True
                rot_controller: True
                # x-direction parameters
                x_min_force: 3.0        # 5.0
                x_max_force: 100.0
                x_max_vel: 1.2
                x_gain: 1.0               # 1/b
                x_time_const: 0.5        # m/b   # 1/(2*pi*Fl)  
                # y-direction parameters
                y_min_force: 3.0        # 5.0
                y_max_force: 100.0
                y_max_vel: 1.2
                y_gain: 1.0              # 1/b
                y_time_const: 0.5        # m/b   # 1/(2*pi*Fl)
                # rotational (z-dir) parameters
                rot_min_torque: 0.1    # 0.5
                rot_max_torque: 40.0
                rot_max_rot_vel: 1.2
                rot_gain: 1.0
                rot_time_const: 0.5
        # parameters for Adaptive FTS controller are to be defined here:
        # all values with a 'scale' in the name are meant as multiplicative values of the respective base value defined in FTSBaseController. Maximum or minimum values for these fields are defined in the comments 
        FTSAdaptiveController:
                use_adaptive_force: False       # whether to use velocity-adaptive force feature
                force_scale_zero_vel: 1.0       # force scaling factor when accelerating from zero [min: 1.0] - higher means heavier
                force_scale_max_vel: 1.0        # force scaling factor when moving close to max vel [max: 1.0] - lower means easier to maintain high speeds
                use_adaptive_mass: False     # whether to use velocity-adaptive mass feature
                mass_scale_min: 1.0          # minimal mass (values <= 1.0 allowed)
                mass_scale_max: 1.0          # maximum mass (values >= 1.0 allowed)
                use_adaptive_damping: False     # whether to use velocity-adaptive damping feature
                damping_scale_min: 1.0          # minimal damping (values <= 1.0 allowed)
                damping_scale_max: 1.0          # maximum damping (values >= 1.0 allowed)
                
        defaults: # default settings for all wheels, can per overwritten per wheel
                steer_ctrl: # Parameters for tuning Impedance-Controller
                        spring: 15.0
                        damp: 2.75
                        virt_mass: 0.1 
                        d_phi_max: 12.0
                        dd_phi_max: 40.0

        wheels: *wheels # start front left, counter-clockwise for base_drive_chain 

## odometry_controller
odometry_controller:
        type: cob_omni_drive_controller/OdometryController
        publish_rate: 50
        frame_id: "/odom_combined"
        child_frame_id: "/base_footprint"
        cov_pose: 0.1
        cov_twist: 0.1
        defaults: # default settings for all wheels, can per overwritten per wheel
                wheel_radius: 0.080 # Radius of the wheels in [m]
        wheels: *wheels
